add emmet-vim plugin for HTML

diff --git a/.local/bin/brightctl b/.local/bin/brightctl
--- a/.local/bin/brightctl
+++ b/.local/bin/brightctl
@@ -10,7 +10,7 @@ oldbrightness=$brightness
 echo "Was $brightness"
 [[ $@ == + ]] && ((brightness=($brightness+5) ))
 [[ $@ == - ]] && ((brightness=($brightness-6) ))
-[[ $@ == -s ]] && (echo $brightness 2>/dev/null > $saved && echo "Saved $saved as $brightness" || echo "Failed. Check your privilege.")
+[[ $@ == -s ]] && (echo $brightness > ~/.local/share/brightness && echo "Saved $saved as $brightness" || echo "Failed. Check your privilege.")
 [[ $@ == -r || $@ == restore || $@ == --restore ]] && brightness=$(cat $saved)
 
 echo $brightness > /sys/class/backlight/*_bl0/brightness 2>/dev/null &&
